apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direct-lab.fullname" . }}-secrets
  labels:
    {{- include "direct-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_PASSWORD: {{ .Values.app.mongoPassword | quote }}
  SMTP_USER: {{ .Values.app.smtp.user | quote }}
  SMTP_PASS: {{ .Values.app.smtp.pass | quote }}
